version: "3"
services:
  client:
    image: index.docker.io/uzorex/systemadminproject-client:latest
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app_net

  api:
    image: index.docker.io/uzorex/systemadminproject-server:latest
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - app_net
  
  nginx:
    image: index.docker.io/uzorex/systemadminproject-nginx:latest
    restart: always
    depends_on:
      - client
      - api
    ports:
      - "3050:80"
    networks:
      - app_net

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30


networks:
  app_net:
    driver: bridge